'use client'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Search, ArrowUpRight } from 'lucide-react'
import SubscriptionStatusBadge from './SubscriptionStatusBadge'

export type CondominioRow = { id: string; name: string; slug: string; createdAt: string; housingUnits: number | null; billingMode: string | null; contractedMonthlyPrice: number | null; status: string; nextPaymentDueAt: string | null; renewalAt: string | null }
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN' })
const date = (v: string | null) => v ? new Date(v).toLocaleDateString('es-MX', { day: 'numeric', month: 'short', year: 'numeric' }) : '—'

export default function CondominiosTable({ rows }: { rows: CondominioRow[] }) {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState('ALL'); const [mode, setMode] = useState('ALL')
  const filtered = useMemo(() => rows.filter(r => r.name.toLowerCase().includes(search.toLowerCase()) && (status === 'ALL' || r.status === status) && (mode === 'ALL' || r.billingMode === mode)), [rows, search, status, mode])
  return <section className="overflow-hidden rounded-2xl border border-neutral-100 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-neutral-100 p-4 lg:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-neutral-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar condominio" className="w-full rounded-xl border border-neutral-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-neutral-900" /></label><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-xl border border-neutral-200 px-3 py-2.5 text-sm"><option value="ALL">Todos los estados</option><option value="LEGACY">Sin configuración</option><option value="PENDING_ACTIVATION">Pendientes</option><option value="ACTIVE">Activos</option><option value="PAST_DUE">Pago vencido</option><option value="SUSPENDED">Suspendidos</option><option value="CANCELED">Cancelados</option></select><select value={mode} onChange={e => setMode(e.target.value)} className="rounded-xl border border-neutral-200 px-3 py-2.5 text-sm"><option value="ALL">Todas las modalidades</option><option value="MONTHLY">Mensual</option><option value="ANNUAL">Anual</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="bg-neutral-50 text-xs uppercase tracking-wide text-neutral-400"><tr>{['Condominio','Viviendas','Modalidad','Precio mensual','Estado','Registro','Próximo pago','Renovación',''].map(x => <th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y divide-neutral-100">{filtered.map(r => <tr key={r.id} className="text-sm text-neutral-600 hover:bg-neutral-50/70"><td className="px-4 py-4"><p className="font-medium text-neutral-900">{r.name}</p><p className="text-xs text-neutral-400">/{r.slug}</p></td><td className="px-4">{r.housingUnits ?? '—'}</td><td className="px-4">{r.billingMode === 'ANNUAL' ? 'Anual' : r.billingMode === 'MONTHLY' ? 'Mensual' : '—'}</td><td className="px-4">{r.contractedMonthlyPrice === null ? '—' : money.format(r.contractedMonthlyPrice)}</td><td className="px-4"><SubscriptionStatusBadge status={r.status} /></td><td className="px-4">{date(r.createdAt)}</td><td className="px-4">{date(r.nextPaymentDueAt)}</td><td className="px-4">{date(r.renewalAt)}</td><td className="px-4"><Link href={`/kotta-staff/condominios/${r.id}`} className="inline-flex items-center gap-1 font-medium text-neutral-900">Detalle <ArrowUpRight className="h-4 w-4" /></Link></td></tr>)}</tbody></table>{filtered.length === 0 && <p className="py-14 text-center text-sm text-neutral-400">No hay condominios con esos filtros.</p>}</div></section>
}

