'use client'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AlertTriangle, CheckCircle2, Loader2 } from 'lucide-react'
import { calculateAnnualCancellationFeeCents, calculateKottaPricing, decimalToCents } from '@/lib/kotta-subscriptions/pricing'
import SubscriptionStatusBadge from './SubscriptionStatusBadge'

type Subscription = { id: string; status: string; housingUnits: number | null; billingMode: string | null; isEnterprise: boolean; baseMonthlyPrice: number | null; discountRate: number | null; contractedMonthlyPrice: number | null; vatRate: number | null; contractSignedAt: string | null; serviceStartedAt: string | null; renewalAt: string | null; nextInvoiceAt: string | null; nextPaymentDueAt: string | null; lastPaymentAt: string | null; suspendedAt: string | null; paymentsCount: number }
type Props = { organizationId: string; subscription: Subscription | null }
const money = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', minimumFractionDigits: 2 })
const isoDate = (value: string | null) => value?.slice(0, 10) ?? ''

export default function CondominioCommercialPanel({ organizationId, subscription }: Props) {
  const router = useRouter(); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [confirm, setConfirm] = useState<Record<string, unknown> | null>(null)
  const [housingUnits, setHousingUnits] = useState(String(subscription?.housingUnits ?? '')); const [billingMode, setBillingMode] = useState(subscription?.billingMode ?? 'MONTHLY'); const [enterprisePrice, setEnterprisePrice] = useState(subscription?.isEnterprise ? String(subscription.baseMonthlyPrice ?? '') : ''); const [signedAt, setSignedAt] = useState(isoDate(subscription?.contractSignedAt ?? null)); const [startedAt, setStartedAt] = useState(isoDate(subscription?.serviceStartedAt ?? null)); const [reason, setReason] = useState('')
  const units = Number(housingUnits); const quote = useMemo(() => { try { return calculateKottaPricing(units, billingMode as 'MONTHLY' | 'ANNUAL', enterprisePrice ? decimalToCents(enterprisePrice) : null) } catch { return null } }, [units, billingMode, enterprisePrice])
  const send = async (body: Record<string, unknown>) => { setLoading(true); setError(null); try { const res = await fetch(`/api/kotta-staff/condominios/${organizationId}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await res.json() as { error?: string }; if (!res.ok) throw new Error(result.error ?? 'No fue posible guardar.'); setConfirm(null); setReason(''); router.refresh() } catch (e) { setError(e instanceof Error ? e.message : 'No fue posible guardar.') } finally { setLoading(false) } }
  const configureBody = { action: 'configure', housingUnits: units, billingMode, enterpriseMonthlyPrice: enterprisePrice || null, contractSignedAt: signedAt, serviceStartedAt: startedAt, reason: 'Configuración comercial confirmada.' }
  const complete = Boolean(subscription?.housingUnits && subscription.billingMode && subscription.contractedMonthlyPrice && subscription.contractSignedAt && subscription.serviceStartedAt && subscription.paymentsCount > 0)
  const currentCents = subscription?.contractedMonthlyPrice ? decimalToCents(subscription.contractedMonthlyPrice) : null
  const newCents = quote?.contractedMonthlyCents ?? null
  const cancellationFee = subscription?.billingMode === 'ANNUAL' && subscription.renewalAt && currentCents ? calculateAnnualCancellationFeeCents(currentCents, Math.max(1, Math.ceil((new Date(subscription.renewalAt).getTime() - Date.now()) / (30.4375 * 86400000)))) : 0
  const due = subscription?.nextPaymentDueAt ? new Date(subscription.nextPaymentDueAt) : null; const suspensionEligible = due ? new Date(due.getTime() + 15 * 86400000) : null
  return <div className="space-y-6"><section className="rounded-2xl border border-neutral-100 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-xl text-[#0F1F34]">Contratación y precio</h2><p className="mt-1 text-sm text-neutral-500">El precio guardado es el snapshot contractual para futuras mensualidades.</p></div><SubscriptionStatusBadge status={subscription?.status ?? 'LEGACY'} /></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-neutral-600">Viviendas<input type="number" min="1" value={housingUnits} onChange={e => setHousingUnits(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-neutral-600">Modalidad<select value={billingMode} onChange={e => setBillingMode(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm"><option value="MONTHLY">Mensual</option><option value="ANNUAL">Anual — 10% descuento</option></select></label>{units > 600 && <label className="text-xs font-medium text-neutral-600 sm:col-span-2">Precio mensual Enterprise acordado<input type="number" min="0.01" step="0.01" value={enterprisePrice} onChange={e => setEnterprisePrice(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label>}<label className="text-xs font-medium text-neutral-600">Firma de contrato<input type="date" value={signedAt} onChange={e => setSignedAt(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-neutral-600">Inicio del servicio<input type="date" value={startedAt} onChange={e => setStartedAt(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label></div>{quote && <div className="mt-5 grid gap-3 rounded-2xl bg-[#F7F9FC] p-5 sm:grid-cols-5">{[['Base', quote.baseMonthlyCents], ['Descuento', `${quote.discountBasisPoints / 100}%`], ['Mensualidad', quote.contractedMonthlyCents], ['IVA', quote.vatCents], ['Total', quote.totalMonthlyCents]].map(([label, value]) => <div key={String(label)}><p className="text-xs text-neutral-400">{label}</p><p className="mt-1 text-sm font-medium text-neutral-900">{typeof value === 'number' ? money.format(value / 100) : value ?? 'Requiere precio'}</p></div>)}{currentCents !== null && newCents !== null && currentCents !== newCents && <p className="sm:col-span-5 text-xs font-medium text-[#FD5F56]">Diferencia contra el contrato actual: {money.format((newCents - currentCents) / 100)} al mes.</p>}</div>}<button type="button" onClick={() => setConfirm(configureBody)} disabled={!quote?.contractedMonthlyCents || !signedAt || !startedAt} className="btn-primary mt-5 px-4 py-2.5 text-sm">Confirmar y guardar contrato</button></section>

  {subscription && <><PaymentForm onSubmit={send} defaultPeriod={isoDate(subscription.nextInvoiceAt ?? subscription.serviceStartedAt).slice(0,7)} expected={quote?.totalMonthlyCents ?? (subscription.contractedMonthlyPrice ? Math.round(subscription.contractedMonthlyPrice * (1 + (subscription.vatRate ?? .16)) * 100) : null)} /><section className="rounded-2xl border border-neutral-100 bg-white p-6"><h2 className="font-display text-xl text-[#0F1F34]">Acciones de servicio</h2>{subscription.status === 'PENDING_ACTIVATION' && <div className="mt-4"><div className="grid gap-2 sm:grid-cols-3">{[['Información comercial', !!subscription.housingUnits], ['Contrato y fecha de inicio', !!subscription.contractSignedAt && !!subscription.serviceStartedAt], ['Primer pago registrado', subscription.paymentsCount > 0]].map(([label, ok]) => <p key={String(label)} className={`flex items-center gap-2 rounded-xl p-3 text-sm ${ok ? 'bg-emerald-50 text-emerald-700' : 'bg-neutral-50 text-neutral-500'}`}><CheckCircle2 className="h-4 w-4" />{label}</p>)}</div><button disabled={!complete} onClick={() => setConfirm({ action: 'activate' })} className="btn-primary mt-4 px-4 py-2.5 text-sm">Activar servicio</button></div>}{['ACTIVE','PAST_DUE'].includes(subscription.status) && <div className="mt-4 flex flex-wrap gap-3"><button onClick={() => setConfirm({ action: 'suspend', forNonPayment: subscription.status === 'PAST_DUE' })} disabled={subscription.status === 'PAST_DUE' && !!suspensionEligible && new Date() < suspensionEligible} className="rounded-xl border border-amber-300 px-4 py-2.5 text-sm font-medium text-amber-800 disabled:opacity-40">Suspender servicio</button>{subscription.billingMode === 'ANNUAL' && <button onClick={() => setConfirm({ action: 'renew' })} className="rounded-xl border border-neutral-200 px-4 py-2.5 text-sm font-medium">Renovar 12 meses</button>}<button onClick={() => setConfirm({ action: 'cancel' })} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-medium text-red-700">Cancelar servicio</button></div>}{subscription.status === 'SUSPENDED' && <div className="mt-4 flex gap-3"><button onClick={() => setConfirm({ action: 'reactivate' })} className="btn-primary px-4 py-2.5 text-sm">Reactivar servicio</button><button onClick={() => setConfirm({ action: 'cancel' })} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-medium text-red-700">Cancelar servicio</button></div>}<div className="mt-5 rounded-xl bg-neutral-50 p-4 text-sm text-neutral-600"><p>Penalización por terminación: <b>{subscription.billingMode === 'MONTHLY' ? '$0.00' : money.format(cancellationFee / 100)}</b></p>{suspensionEligible && <p className="mt-1">Elegible para suspensión por mora: {suspensionEligible.toLocaleDateString('es-MX', { dateStyle: 'long' })}</p>}</div></section></>}

  {confirm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><AlertTriangle className="h-5 w-5 text-[#FD5F56]" /><h3 className="mt-3 font-display text-xl text-neutral-900">Confirmar acción comercial</h3><p className="mt-2 text-sm text-neutral-500">Este cambio quedará registrado en el historial de auditoría.</p>{['suspend','cancel','reactivate','renew'].includes(String(confirm.action)) && <textarea value={reason} onChange={e => setReason(e.target.value)} placeholder={['suspend','cancel'].includes(String(confirm.action)) ? 'Motivo obligatorio' : 'Nota o motivo'} className="mt-4 min-h-24 w-full rounded-xl border border-neutral-200 p-3 text-sm" />}{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button disabled={loading} onClick={() => { setConfirm(null); setError(null) }} className="rounded-xl px-4 py-2 text-sm">Volver</button><button disabled={loading || (['suspend','cancel'].includes(String(confirm.action)) && !reason.trim())} onClick={() => send({ ...confirm, reason })} className="btn-primary px-4 py-2 text-sm">{loading ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Confirmar'}</button></div></div></div>}</div>
}

function PaymentForm({ onSubmit, defaultPeriod, expected }: { onSubmit: (body: Record<string, unknown>) => void; defaultPeriod: string; expected: number | null }) { const [period, setPeriod] = useState(defaultPeriod); const [amount, setAmount] = useState(expected ? (expected / 100).toFixed(2) : ''); const [paidAt, setPaidAt] = useState(new Date().toISOString().slice(0,10)); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); return <section className="rounded-2xl border border-neutral-100 bg-white p-6"><h2 className="font-display text-xl text-[#0F1F34]">Registrar transferencia recibida</h2><p className="mt-1 text-sm text-neutral-500">Registro administrativo; no realiza ninguna operación bancaria.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-medium text-neutral-600">Periodo<input type="month" value={period} onChange={e => setPeriod(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-neutral-600">Importe recibido<input type="number" min="0.01" step="0.01" value={amount} onChange={e => setAmount(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-neutral-600">Fecha de pago<input type="date" value={paidAt} onChange={e => setPaidAt(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-neutral-600">Referencia bancaria<input value={reference} onChange={e => setReference(e.target.value)} className="mt-1.5 w-full rounded-xl border border-neutral-200 px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium text-neutral-600 sm:col-span-2">Notas<textarea value={notes} onChange={e => setNotes(e.target.value)} className="mt-1.5 min-h-20 w-full rounded-xl border border-neutral-200 p-3 text-sm" /></label></div><button disabled={!period || !amount || !paidAt} onClick={() => onSubmit({ action: 'record_payment', period, amountReceived: amount, paidAt, bankReference: reference, notes })} className="btn-primary mt-5 px-4 py-2.5 text-sm">Registrar pago</button></section> }
